Fix variable mistakes & allow configuration to be passed

diff --git a/dunit b/dunit
--- a/dunit
+++ b/dunit
@@ -7,11 +7,40 @@ SCRIPTPATH=`dirname $SCRIPT`
 #Default PHP versions
 phpVersion="5.3 5.4 5.5 5.6"
 dockerMountPath=$(pwd)
+syntaxOnly=false
 phpUnitCommand="/opt/source/vendor/bin/phpunit"
 phpSyntaxCommand="find ${dockerMountPath} -iname '*.php' -exec php -l {} \; | grep -i 'Parse error'"
+configPath="${SCRIPTPATH}/.config"
 
-if [ -a "${SCRIPTPATH}/.config" ];
-  then source "${SCRIPTPATH}/.config"
+#getopt That allows the options to be passed
+while getopts ":hp:c:" opt; do
+  shift $((OPTIND-1))
+  case ${opt} in
+    h)
+      printf "Options:\n"
+      printf "%-20s %-40s\n" '-h' 'Displays help information'
+      printf "%-20s %-40s\n" '-p' 'PHP Versions you wish to use (default: "5.3 5.4 5.5 5.6")'
+      exit 0;
+      ;;
+    p)
+      phpVersion=$OPTARG
+      ;;
+    c)
+      configPath=$OPTARG
+      ;;
+    \?)
+      printf "Invalid option: -$OPTARG\n"
+      exit 1
+      ;;
+    :)
+      printf "Option -$OPTARG requires an argument.\n"
+      exit 1
+      ;;
+  esac
+done
+
+if [ -a "${configPath}" ];
+  then source ${configPath}
 fi;
 
 #Config & Global overwrite
@@ -24,36 +53,12 @@ if [ -n "${DUNIT_SYNTAXONLY}" ];
 fi
 
 if [ -n "${DUNIT_PHPUNITCOMMAND}" ];
-  then phpUnitPath=${DUNIT_PHPUNITPATH}
+  then phpUnitCommand=${DUNIT_PHPUNITCOMMAND}
 fi
 
 if [ -n "${DUNIT_PHPSYNTAXCOMMAND}" ];
-  then phpUnitPath=${DUNIT_PHPUNITPATH}
+  then phpSyntaxCommand=${DUNIT_PHPSYNTAXCOMMAND}
 fi
-
-#getopt That allows the options to be passed
-while getopts ":hp:" opt; do
-  shift $((OPTIND-1))
-  case ${opt} in
-    h)
-      printf "Options:\n"
-      printf "%-20s %-40s\n" '-h' 'Displays help information'
-      printf "%-20s %-40s\n" '-p' 'PHP Versions you wish to use (default: "5.3 5.4 5.5 5.6")'
-      exit 0;
-      ;;
-    p)
-      phpVersion=$OPTARG
-      ;;
-    \?)
-      printf "Invalid option: -$OPTARG\n"
-      exit 1
-      ;;
-    :)
-      printf "Option -$OPTARG requires an argument.\n"
-      exit 1
-      ;;
-  esac
-done
 
 #Allow path to be passed to docker for mounting
 if [ -n "$1" ];
